/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import api.*;
import api.CallMeal;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import controller.JsonGson;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Meals;
import service.DB;

/**
 *
 * @author Dia
 */
public class ChooseMealGUI extends javax.swing.JFrame {
//    DB.connect();

    /**
     * Creates new form ChooseMealGUI
     */
    public ChooseMealGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textForMeal = new javax.swing.JTextField();
        searchForMeal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        chooseFromComboBox = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showMealName = new javax.swing.JTextField();
        showCategory = new javax.swing.JTextField();
        showAreaInfo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        showInstructions = new javax.swing.JTextArea();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Meal");

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        jLabel1.setText("Choose a meal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name of the meal :");

        textForMeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textForMeal.setText("spaghetti");
        textForMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textForMealActionPerformed(evt);
            }
        });

        searchForMeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchForMeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mealapp/search.png"))); // NOI18N
        searchForMeal.setText("Search");
        searchForMeal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchForMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchForMealActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mealapp/dinner.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Results :");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        chooseFromComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chooseFromComboBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mealapp/choose.png"))); // NOI18N
        chooseFromComboBox.setText("Choose");
        chooseFromComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chooseFromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFromComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        jLabel5.setText("Meal details");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Name :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Category : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Area of origin :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Cooking Instructions : ");

        showMealName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMealNameActionPerformed(evt);
            }
        });

        showCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCategoryActionPerformed(evt);
            }
        });

        showAreaInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAreaInfoActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mealapp/save.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mealapp/delete.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mealapp/edit.png"))); // NOI18N
        jButton5.setText("Edit");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        showInstructions.setColumns(20);
        showInstructions.setRows(5);
        jScrollPane1.setViewportView(showInstructions);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(showAreaInfo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textForMeal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 366, Short.MAX_VALUE)
                                    .addComponent(showMealName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showCategory, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chooseFromComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(searchForMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textForMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchForMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(showMealName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(showCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(showAreaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchForMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchForMealActionPerformed
        try{
         Api call = new CallMeal();
         JsonGson gs = new JsonGson();
         
//        Παίρνουμε τα δεδομένα της αναζήτησης του χρήστη
        String name = textForMeal.getText().trim();
        
//        Κλήση του API kai μορφοποίηση δεδομένων
        String responseString = call.callHttp(name); 
        JsonObject json = gs.gsonCall(responseString);
        
        // Καταχωρώ της εγγρφές του Array meals
        JsonArray jArray = json.get("meals").getAsJsonArray();
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        //Διατρέχουμε κάθε εγγραφή και παίρνουμε το όνομα για τον αντιστιχήσουμε
        // στο dropDown menu με κάθε γεύμα 
//        / Εαν η αναζήτηση επιστρέφει μόνο ένα γεύμα 
//          τότε εμφανίζει το αποτελέσμα ΑΝΑΖΉΤΗΣΗΣ 
        if(!(jArray.size()== 1)){
        for (JsonElement jsonElement : jArray) {
                        JsonObject jsonObj = jsonElement.getAsJsonObject();
                        String nameOfMeal = jsonObj.get("strMeal").getAsString();
                        model.addElement(nameOfMeal); 
                    }
        // εμφανίζει τα αποτελέσματα στο dropDown Menu
        String selectedValue = jComboBox1.getSelectedItem().toString();
        jComboBox1.setModel(model);
                }
        //   αλιώς καταχωρελί στο dropwdown menu όλα τα αποτελέσματα 
        else {
            for (var jsonElement : jArray) {
                                JsonObject jsonObj = jsonElement.getAsJsonObject();
                                String strMeal = jsonObj.get("strMeal").getAsString();
                                showMealName.setText(strMeal);
                                String strCategory = jsonObj.get("strCategory").getAsString();
                                showCategory.setText(strCategory);
                                String strArea = jsonObj.get("strArea").getAsString();
                                showAreaInfo.setText(strArea);
                                String strInstructions = jsonObj.get("strInstructions").getAsString();
                                showInstructions.setText(strInstructions);
                            }
        }
        }catch(IllegalStateException e){
            String message = "No Result! \n" 
                    + "Wrong Name of Meal, please try again with correct name."
                    + "\nOr check \"meals by category\".";
            JOptionPane.showMessageDialog(rootPane, message);
        }
        
    }//GEN-LAST:event_searchForMealActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // επιλέγουμε το γεύμα μόνο με  κλίκ με το ποντίκι 
        Object object = evt.getSource();
            if (object == jComboBox1) {
                chooseFromComboBoxActionPerformed(evt);

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void showMealNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMealNameActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_showMealNameActionPerformed

    private void showCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showCategoryActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void showAreaInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAreaInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAreaInfoActionPerformed

    private void textForMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textForMealActionPerformed
        // Επιλέγουμε και με ENTER το κείμενο προς αναζήτηση
        Object object = evt.getSource();
            if (object == textForMeal) {
                searchForMealActionPerformed(evt);

        }
    }//GEN-LAST:event_textForMealActionPerformed

    private void chooseFromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFromComboBoxActionPerformed
try {
//            Query query = em.createNamedQuery("Meal.findByStrmeal");
//            query.setParameter("strmeal", jComboBox1.getSelectedItem().toString());
//
//            //Ελέγχουμε εάν υπάρχουν δεδομένα στην Database
//            if (query.getResultList().isEmpty()) {
        Api call = new CallMeal();
         JsonGson gs = new JsonGson();

//        Παίρνουμε τα δεδομένα της αναζήτησης του χρήστη από το comboBox
        String mealName = jComboBox1.getSelectedItem().toString();
        
//        Κλήση του API kai μορφοποίηση δεδομένων
        String responseString = call.callHttp(mealName); 
        JsonObject json = gs.gsonCall(responseString);
        
        // Καταχωρώ της εγγρφές του Array meals
        JsonArray jArray = json.get("meals").getAsJsonArray();
        
        
        //Διαπερνώ τα meals και 
        //Βάζω τις εγγραφές του πίνακα στα αντοίστιχα fileds
                            for (var jsonElement : jArray) {
                                JsonObject m = jsonElement.getAsJsonObject();
                                String strMeal = m.get("strMeal").getAsString();
                                showMealName.setText(strMeal);
                                String strCategory = m.get("strCategory").getAsString();
                                showCategory.setText(strCategory);
                                String strArea = m.get("strArea").getAsString();
                                showAreaInfo.setText(strArea);
                                String strInstructions = m.get("strInstructions").getAsString();
                                showInstructions.setText(strInstructions);
                            }
//            }
//            else {
//                //Εντοπίζω το αντικείμενο
//                Meals meal = (Meals) query.getSingleResult();
//                //Αυξάνω την προβολή του Γεύματος
//////////////////meal.counter();
////Ενημερώνω το γεύμα στην βάση
//                mealController.edit(meal);
//                
//                //Στέλνω τις πληροφορίες του γεύματος στο GUI
//                String idMeal = meal.getIdmeal().toString();
//                jTextField5.setText(idMeal);
//                String strMeal = meal.getStrmeal();
//                jTextField2.setText(strMeal);
//                String strCategory = meal.getStrcategory();
//                jTextField3.setText(strCategory);
//                String strArea = meal.getStrarea();
//                jTextField4.setText(strArea);
//                String strInstructions = meal.getStrinstructions();
//                jTextArea1.setText(strInstructions);
//            }
                    } catch (Exception e) {
                        System.out.println(e);
                    }

    }//GEN-LAST:event_chooseFromComboBoxActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseMealGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseMealGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseMealGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseMealGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseMealGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton chooseFromComboBox;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchForMeal;
    private javax.swing.JTextField showAreaInfo;
    private javax.swing.JTextField showCategory;
    private javax.swing.JTextArea showInstructions;
    private javax.swing.JTextField showMealName;
    private javax.swing.JTextField textForMeal;
    // End of variables declaration//GEN-END:variables
}
